import React, { useState, useEffect } from 'react';
import { projectAPI, taskAPI } from '../services/api';
import { useAuth } from '../context/AuthContext';
import { toast } from 'react-hot-toast';
import { BarChart3, FileText, Download, FileSpreadsheet, TrendingUp } from 'lucide-react';
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
  Legend
} from 'recharts';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';

const Reports = () => {
  const { user } = useAuth();
  
  const [projects, setProjects] = useState([]);
  const [tasks, setTasks] = useState([]);
  const [loading, setLoading] = useState(true);

  // Charts data states
  const [priorityData, setPriorityData] = useState([]);
  const [statusData, setStatusData] = useState([]);

  const COLORS = ['#10b981', '#3b82f6', '#f59e0b', '#ef4444'];

  const loadReportData = async () => {
    try {
      const [projRes, tasksRes] = await Promise.all([
        projectAPI.getAll(),
        taskAPI.getAll()
      ]);

      if (projRes.data.success) {
        setProjects(projRes.data.projects);
      }

      if (tasksRes.data.success) {
        const fetchedTasks = tasksRes.data.tasks;
        setTasks(fetchedTasks);

        // Compile Priority Distribution Chart
        const priorityCounts = { Critical: 0, High: 0, Medium: 0, Low: 0 };
        // Compile Status Distribution Chart
        const statusCounts = { Pending: 0, 'In Progress': 0, Completed: 0 };

        fetchedTasks.forEach(t => {
          if (priorityCounts[t.priority] !== undefined) {
            priorityCounts[t.priority]++;
          }
          if (statusCounts[t.status] !== undefined) {
            statusCounts[t.status]++;
          }
        });

        setPriorityData([
          { name: 'Critical', value: priorityCounts.Critical },
          { name: 'High', value: priorityCounts.High },
          { name: 'Medium', value: priorityCounts.Medium },
          { name: 'Low', value: priorityCounts.Low }
        ].filter(d => d.value > 0));

        setStatusData([
          { name: 'Backlog / Pending', count: statusCounts.Pending, fill: '#f59e0b' },
          { name: 'In Progress', count: statusCounts['In Progress'], fill: '#3b82f6' },
          { name: 'Completed', count: statusCounts.Completed, fill: '#10b981' }
        ]);
      }
    } catch (error) {
      console.error('Failed to compile report summaries:', error);
      toast.error('Failed to load workspace reports.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadReportData();
  }, []);

  // ── GENERATE PDF REPORT ──
  const handleExportPDF = () => {
    if (projects.length === 0 && tasks.length === 0) {
      toast.error('No workspace data to export.');
      return;
    }

    try {
      const doc = new jsPDF();
      const pageTitle = 'SprintHub Workspace Academic Report';
      const timestamp = new Date().toLocaleString();

      // Report Title page branding
      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(22);
      doc.setTextColor(124, 58, 237); // Primary color theme
      doc.text('SprintHub Project Report', 20, 25);

      doc.setFontSize(10);
      doc.setFont('Helvetica', 'normal');
      doc.setTextColor(100, 116, 139);
      doc.text(`Generated by: ${user.name} (${user.email})`, 20, 32);
      doc.text(`Timestamp: ${timestamp}`, 20, 38);
      doc.text(`Database Mode: Full-Stack Hybrid Workspace`, 20, 44);

      // Line Separator
      doc.setDrawColor(226, 232, 240);
      doc.line(20, 48, 190, 48);

      // SECTION 1: PROJECTS SUMMARY TABLE
      doc.setFontSize(14);
      doc.setFont('Helvetica', 'bold');
      doc.setTextColor(15, 23, 42);
      doc.text('1. Project Boards Milestone Summary', 20, 58);

      const projectHeaders = [['Project Name', 'Category', 'Priority', 'Status', 'Deadline', 'Progress']];
      const projectRows = projects.map(p => [
        p.name,
        p.category || 'General',
        p.priority,
        p.status,
        p.deadline ? new Date(p.deadline).toLocaleDateString() : '--',
        `${p.progress}%`
      ]);

      autoTable(doc, {
        head: projectHeaders,
        body: projectRows,
        startY: 63,
        theme: 'striped',
        headStyles: { fillColor: [124, 58, 237] },
        styles: { fontSize: 9 }
      });

      // SECTION 2: TASKS SUMMARY TABLE (Starts after the first table)
      const finalY = doc.lastAutoTable.finalY + 15;
      doc.setFontSize(14);
      doc.setFont('Helvetica', 'bold');
      doc.text('2. Tasks Milestone Execution Log', 20, finalY);

      const taskHeaders = [['Task Title', 'Project Link', 'Priority', 'Status', 'Deadline']];
      const taskRows = tasks.map(t => {
        const linkedProject = projects.find(p => p.id === t.projectId)?.name || 'General Board';
        return [
          t.title,
          linkedProject,
          t.priority,
          t.status,
          t.deadline ? new Date(t.deadline).toLocaleDateString() : '--'
        ];
      });

      autoTable(doc, {
        head: taskHeaders,
        body: taskRows,
        startY: finalY + 5,
        theme: 'striped',
        headStyles: { fillColor: [8, 145, 178] }, // Cyan color accent
        styles: { fontSize: 9 }
      });

      // Save PDF
      doc.save(`SprintHub_Report_${Date.now()}.pdf`);
      toast.success('PDF report downloaded successfully! 📄');
    } catch (error) {
      console.error('PDF export crashed:', error);
      toast.error('Failed to generate PDF document.');
    }
  };

  // ── GENERATE EXCEL WORKBOOK ──
  const handleExportExcel = () => {
    if (projects.length === 0 && tasks.length === 0) {
      toast.error('No workspace data to export.');
      return;
    }

    try {
      const wb = XLSX.utils.book_new();

      // Sheet 1: Projects Data
      const projectSheetData = projects.map(p => ({
        'Project Name': p.name,
        'Description': p.description || '',
        'Category': p.category || 'General',
        'Status': p.status,
        'Priority': p.priority,
        'Start Date': p.startDate ? new Date(p.startDate).toLocaleDateString() : '--',
        'Deadline': p.deadline ? new Date(p.deadline).toLocaleDateString() : '--',
        'Milestone Progress': `${p.progress}%`,
        'Estimated Hours': p.estimatedHours || 0
      }));
      const wsProjects = XLSX.utils.json_to_sheet(projectSheetData);
      XLSX.utils.book_append_sheet(wb, wsProjects, 'Projects Summary');

      // Sheet 2: Tasks Data
      const taskSheetData = tasks.map(t => {
        const linkedProject = projects.find(p => p.id === t.projectId)?.name || 'General Board';
        return {
          'Task Title': t.title,
          'Description': t.description || '',
          'Project Link': linkedProject,
          'Status': t.status,
          'Priority': t.priority,
          'Deadline': t.deadline ? new Date(t.deadline).toLocaleDateString() : '--',
          'Completed At': t.completedAt ? new Date(t.completedAt).toLocaleDateString() : 'Pending'
        };
      });
      const wsTasks = XLSX.utils.json_to_sheet(taskSheetData);
      XLSX.utils.book_append_sheet(wb, wsTasks, 'Tasks Detailed List');

      // Write workbook file
      XLSX.writeFile(wb, `SprintHub_Workspace_Log_${Date.now()}.xlsx`);
      toast.success('Excel workbook downloaded successfully! 📊');
    } catch (error) {
      console.error('Excel export crashed:', error);
      toast.error('Failed to generate Excel sheet.');
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[60vh]">
        <div className="flex flex-col items-center gap-3">
          <div className="w-10 h-10 border-4 border-primary-200 border-t-primary-600 rounded-full animate-spin" />
          <span className="text-xs font-semibold text-gray-500">Formulating report indices...</span>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-8 animate-fade-in">
      
      {/* Header with actions */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h2 className="text-xl md:text-2xl font-extrabold tracking-tight text-gray-950 dark:text-white flex items-center gap-2.5">
            <BarChart3 className="w-6 h-6 text-primary-500" /> Workspace Analytics
          </h2>
          <p className="text-xs text-gray-500 mt-0.5">Track project milestones and compile official PDF/Excel archives</p>
        </div>

        <div className="flex gap-3 w-full sm:w-auto">
          <button
            onClick={handleExportPDF}
            className="flex-1 sm:flex-grow-0 px-4 py-2.5 rounded-xl text-xs font-bold btn-gradient flex items-center justify-center gap-2"
          >
            <Download className="w-4 h-4" /> Download PDF Report
          </button>
          
          <button
            onClick={handleExportExcel}
            className="flex-1 sm:flex-grow-0 px-4 py-2.5 rounded-xl text-xs font-bold btn-gradient-secondary flex items-center justify-center gap-2"
          >
            <FileSpreadsheet className="w-4 h-4 text-emerald-500" /> Export Excel Log
          </button>
        </div>
      </div>

      {/* Visual Charts Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        
        {/* Status Counts */}
        <div className="glass-card p-6 flex flex-col">
          <h3 className="text-sm font-extrabold text-gray-950 dark:text-white uppercase tracking-wider mb-5 flex items-center gap-2">
            <TrendingUp className="w-4.5 h-4.5 text-primary-500" /> Tasks Status Ratios
          </h3>
          <div className="h-[250px] w-full text-xs">
            {tasks.length === 0 ? (
              <div className="flex items-center justify-center h-full text-gray-400">
                No task status metrics logged.
              </div>
            ) : (
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={statusData}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="rgba(255,255,255,0.05)" />
                  <XAxis dataKey="name" stroke="transparent" tick={{ fill: '#888888', fontSize: 10 }} />
                  <YAxis stroke="transparent" tick={{ fill: '#888888', fontSize: 10 }} />
                  <Tooltip 
                    contentStyle={{ 
                      backgroundColor: 'rgba(30, 30, 46, 0.9)', 
                      borderRadius: '12px', 
                      border: '1px solid rgba(255,255,255,0.1)',
                      color: '#fff'
                    }} 
                  />
                  <Bar dataKey="count" radius={[8, 8, 0, 0]} barSize={40} />
                </BarChart>
              </ResponsiveContainer>
            )}
          </div>
        </div>

        {/* Priority Counts */}
        <div className="glass-card p-6 flex flex-col">
          <h3 className="text-sm font-extrabold text-gray-950 dark:text-white uppercase tracking-wider mb-5 flex items-center gap-2">
            <BarChart3 className="w-5 h-5 text-primary-500" /> Tasks Priority Breakdown
          </h3>
          <div className="h-[250px] w-full text-xs flex items-center justify-center">
            {priorityData.length === 0 ? (
              <div className="text-gray-400">
                No task priority metrics logged.
              </div>
            ) : (
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={priorityData}
                    cx="50%"
                    cy="50%"
                    innerRadius={60}
                    outerRadius={80}
                    paddingAngle={5}
                    dataKey="value"
                  >
                    {priorityData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip 
                    contentStyle={{ 
                      backgroundColor: 'rgba(30, 30, 46, 0.9)', 
                      borderRadius: '12px', 
                      border: '1px solid rgba(255,255,255,0.1)',
                      color: '#fff'
                    }}
                  />
                  <Legend verticalAlign="bottom" height={36} />
                </PieChart>
              </ResponsiveContainer>
            )}
          </div>
        </div>
      </div>

      {/* Summary table summaries */}
      <div className="glass-card p-6">
        <h3 className="text-sm font-extrabold text-gray-950 dark:text-white uppercase tracking-wider mb-4.5">
          Milestone Overview Logs
        </h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-8 text-xs font-medium text-gray-600 dark:text-gray-400">
          <div className="p-4 rounded-xl border border-gray-100 dark:border-gray-800 bg-gray-50/20 dark:bg-dark-300/10 space-y-2">
            <span className="font-bold text-gray-800 dark:text-gray-200 text-sm block">Project Board Index</span>
            <div className="flex justify-between">
              <span>Total Active Boards:</span>
              <span className="font-bold text-primary-500">{projects.length}</span>
            </div>
            <div className="flex justify-between">
              <span>Completed Projects:</span>
              <span className="font-bold text-emerald-500">{projects.filter(p => p.status === 'Completed').length}</span>
            </div>
          </div>

          <div className="p-4 rounded-xl border border-gray-100 dark:border-gray-800 bg-gray-50/20 dark:bg-dark-300/10 space-y-2">
            <span className="font-bold text-gray-800 dark:text-gray-200 text-sm block">Task Execution Log</span>
            <div className="flex justify-between">
              <span>Total Work Tasks:</span>
              <span className="font-bold text-cyan-500">{tasks.length}</span>
            </div>
            <div className="flex justify-between">
              <span>Pending Backlog:</span>
              <span className="font-bold text-orange-500">{tasks.filter(t => t.status !== 'Completed').length}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Reports;
